version: "3"

services:
  postgres:
    image: postgres:9.6-alpine
    networks:
      - database
    container_name: database-postgres
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB:postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    networks:
      - client-web
    ports:
      - "3000:3000"
    restart: on-failure
    image: rafaelwesslingmeurer/web
    volumes:
      - /app/node_modules
      - ./web:/app
    environment:
      - API_HOST=http://localhost:3001
      - PORT=3000
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - service-api
      - database
    ports:
      - "3001:3001"
    restart: on-failure
    image: rafaelwesslingmeurer/api
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - DB=postgres://postgres:postgres@database-postgres:5432/postgres
      - PORT=3001
    depends_on: 
      - postgres

networks:
  client-web:
    driver: bridge
  service-api:
    driver: bridge
  database:
    driver: bridge
